Add a simple doc on the convex poly constraints.
viblo/pymunk pull request #264
Opened 2024-11-07 06:06 UTC by VeriTas-arch

## Contents

- A simple note (line 582) on that polys can only be convex (see issue here #257 ), yet the doc content can be further discussed.
- Some minor changes on the doc to unify the style.

2024-11-08 08:13 UTC, VeriTas-arch reviewed
Most of them are minor changes.

2024-11-09 09:09 UTC, viblo requested changes
A minor comment

2024-11-09 09:09 UTC, viblo commented on pymunk/shapes.py
> +        Add a small radius will bevel the corners and can significantly
I think Adding is the correct way here. This is what the user would need pass in to this method, not what the method does.

2024-11-09 12:21 UTC, VeriTas-arch reviewed
> I think Adding is the correct way here. This is what the user would need pass in to this method, not what the method does.


Well, it is in deed an omission, which is fixed already.

2024-11-09 22:40 UTC, viblo approved these changes

2024-11-09 22:40 UTC, merged

2024-11-09 22:41 UTC, viblo commented
Thanks for the PR!